### PR TITLE
Don't stop MediaPlayers before releasing them

### LINKED ISSUE #5298: NPE: answering or rejecting an incoming call crashes (ICS)
I have:
- [x] searched open and closed issues for duplicates (there are so many :cold_sweat:)
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
All incoming Signal calls to my ICS device crash (**edit: when the device is in silent or in vibration mode**). Doesn't matter if I reject them or answer them, Signal always crashes. After the crash I see a call notification in the system status bar that's stuck and doesn't go away unless I make a new Signal call to someone.
~~No idea when this crashing has started. Last time I tried calls with this device was 3.4 or 3.5 or somewhere around there...~~
**edit: 3.9.1 does not crash, in 3.10.0 the crashing appears the first time**

### Steps to reproduce
1. Place a Signal call to my ICS device
1. Answer or reject the call on the ICS device
1. ICS device's Signal crashes

### Device info
Huawei U8800, Android 4.0.4, since Signal 3.10.0

### Debug log
https://gist.github.com/anonymous/5f2ea45724d47f4104ac

**When answering:**
```
E/AndroidRuntime( 9118): FATAL EXCEPTION: Thread-556
E/AndroidRuntime( 9118): java.lang.NullPointerException
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.audio.IncomingRinger.stop(IncomingRinger.java:113)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.handleAnswerCall(RedPhoneService.java:253)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:148)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:77)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:525)
E/AndroidRuntime( 9118): 	at java.lang.Thread.run(Thread.java:856)
```
**When rejecting:**
```
E/AndroidRuntime( 9519): FATAL EXCEPTION: Thread-582
E/AndroidRuntime( 9519): java.lang.NullPointerException
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.audio.IncomingRinger.stop(IncomingRinger.java:113)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.handleDenyCall(RedPhoneService.java:262)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:149)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:77)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:525)
E/AndroidRuntime( 9519): 	at java.lang.Thread.run(Thread.java:856)
```

### PR DESCRIPTION
**Pull request by haffenloher**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Emulator, Android 5.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the Bithub reward or not by omitting or adding the word `FREEBIE` in my commit message

----------

### Description

I hope this fixes #5298, but I couldn't reproduce the crash. @2-4601 could you please test this?

// FREEBIE

### CODE REVIEW

**Comment by 2-4601** [comment]
It does indeed fix it :+1: :ice_cream: :beers: :tada:

File: src/org/thoughtcrime/redphone/audio/OutgoingRinger.java [hunk 1]
```diff
@@ -114,7 +114,6 @@ private void start() {
   public void stop() {
     if( mediaPlayer == null ) return;
     try {
-      mediaPlayer.stop();
```
Comment (cascheberg) [inline src/org/thoughtcrime/redphone/audio/OutgoingRinger.java]: You can then also remove the `try...catch` for `IllegalStateException`.

**Comment by haffenloher** [comment]
@2-4601 thanks =)
@cascheberg :+1: done
